production:
  client_id: 38930
  client_secret: 36207df30a
  authorize_redirect_uri: "http://dev.noisebytes.com/wepay/authorize"
  scope: ['refund_payments','collect_payments','view_balance','view_user']
  #wepay_api_uri: "https://api.wepay.com"
  wepay_api_uri: "https://stage.wepay.com"
  wepay_api_version: "v2"
  ipn_callback_uri: "http://www.noisebytes.com/wepay/ipn"
  checkout_redirect_uri: "http://www.noisebytes.com/purchase/finalize"
  fee_payer: Payee
  checkout_type: GOODS
  charge_tax: false
  app_fee: 0
  auto_capture: true
  require_shipping: false
  shipping_fee: 0
  charge_tax: false
development:
  client_id: 38930
  client_secret: 36207df30a
  redirect_uri: "http://dev.noisebytes.com/wepay/authorize"
  scope: ['refund_payments','collect_payments','view_balance','view_user']
  wepay_api_uri: "https://stage.wepay.com"
  wepay_api_version: "v2"
  ipn_callback_uri: "http://dev.noisebytes.com/wepay/ipn"
  checkout_redirect_uri: "http://dev.noisebytes.com/purchase/finalize"
  fee_payer: Payee
  checkout_type: GOODS
  charge_tax: false
  app_fee: 0
  require_shipping: false
  shipping_fee: 0
  charge_tax: false
  auto_capture: true
test:
  client_id: 38930
  client_secret: 36207df30a
  redirect_uri: "http://dev.noisebytes.com/wepay/authorize"
  scope: ['refund_payments','collect_payments','view_balance','view_user']
  wepay_api_uri: "https://stage.wepay.com"
  wepay_api_version: "v2"
  ipn_callback_uri: "http://test.noisebytes.com/wepay/ipn"
  checkout_redirect_uri: "http://dev.noisebytes.com/purchase/finalize"
  fee_payer: Payee
  checkout_type: GOODS
  charge_tax: false
  app_fee: 0
  auto_capture: true
  charge_tax: false
  require_shipping: false
  shipping_fee: 0
