production:
  client_id: 38930
  client_secret: 36207df30a
  redirect_uri: "http://dev.noisebytes.com/wepay/authorize"
  scope: ['refund_payments','collect_payments','view_balance','view_user']
  #wepay_api_uri: "https://api.wepay.com"
  wepay_api_uri: "https://stage.wepay.com"
  wepay_api_version: "v2"
development:
  client_id: 38930
  client_secret: 36207df30a
  redirect_uri: "http://dev.noisebytes.com/wepay/authorize"
  scope: ['refund_payments','collect_payments','view_balance','view_user']
  wepay_api_uri: "https://stage.wepay.com"
  wepay_api_version: "v2"
test:
  client_id: 38930
  client_secret: 36207df30a
  redirect_uri: "http://dev.noisebytes.com/wepay/authorize"
  scope: ['refund_payments','collect_payments','view_balance','view_user']
  wepay_api_uri: "https://stage.wepay.com"
  wepay_api_version: "v2"
